/* Electrical formulas. `num` comes from engine.js. */
registerFormulas([
  {
    id: 'electrical-power',
    topic: 'electrical',
    name: 'Electrical Power',
    desc: 'Power from voltage and current',
    keywords: 'electrical power watts voltage current p=vi wattage',
    eq: 'P = V · I',
    inputs: [
      { key: 'V', label: 'Voltage', unit: 'V', hint: 'e.g. 230' },
      { key: 'I', label: 'Current', unit: 'A', hint: 'e.g. 10' },
    ],
    output: { label: 'Power', unit: 'W' },
    compute: v => v.V * v.I,
    format: num,
  },
  {
    id: 'ohms-voltage',
    topic: 'electrical',
    name: "Ohm's Law (Voltage)",
    desc: 'Voltage from current and resistance',
    keywords: 'ohm law voltage volts current resistance v=ir',
    eq: 'V = I · R',
    inputs: [
      { key: 'I', label: 'Current', unit: 'A', hint: 'e.g. 2' },
      { key: 'R', label: 'Resistance', unit: 'Ω', hint: 'e.g. 100' },
    ],
    output: { label: 'Voltage', unit: 'V' },
    compute: v => v.I * v.R,
    format: num,
  },
  {
    id: 'ohms-resistance',
    topic: 'electrical',
    name: "Ohm's Law (Resistance)",
    desc: 'Resistance from voltage and current',
    keywords: 'ohm law resistance ohms voltage current r=v/i',
    eq: 'R = V / I',
    inputs: [
      { key: 'V', label: 'Voltage', unit: 'V', hint: 'e.g. 230' },
      { key: 'I', label: 'Current', unit: 'A', hint: 'e.g. 5' },
    ],
    output: { label: 'Resistance', unit: 'Ω' },
    compute: v => v.V / v.I,
    format: num,
  },
  {
    id: 'electrical-energy',
    topic: 'electrical',
    name: 'Electrical Energy',
    desc: 'Energy used by a device over time',
    keywords: 'electrical energy consumption kwh watt hours power time bill usage',
    eq: 'E = P · t',
    inputs: [
      { key: 'P', label: 'Power', unit: 'W', hint: 'e.g. 2000' },
      { key: 't', label: 'Time', unit: 'hours', hint: 'e.g. 3' },
    ],
    output: { label: 'Energy', unit: 'Wh' },
    compute: v => v.P * v.t,
    format: num,
  },
  {
    id: 'capacitor-charge',
    topic: 'electrical',
    name: 'Capacitor Charge',
    desc: 'Charge stored on a capacitor',
    keywords: 'capacitor charge coulombs capacitance voltage q=cv store',
    eq: 'Q = C · V',
    inputs: [
      { key: 'C', label: 'Capacitance', unit: 'F', hint: 'e.g. 0.001' },
      { key: 'V', label: 'Voltage', unit: 'V', hint: 'e.g. 12' },
    ],
    output: { label: 'Charge', unit: 'C' },
    compute: v => v.C * v.V,
    format: num,
  },
]);
