/* Geometry formulas. `num` comes from engine.js. */
registerFormulas([
  {
    id: 'circle-area',
    topic: 'geometry',
    name: 'Circle Area',
    desc: 'Area from radius',
    keywords: 'circle area pi radius round disc surface',
    eq: 'A = π · r²',
    inputs: [
      { key: 'r', label: 'Radius', unit: '', hint: 'e.g. 5' },
    ],
    output: { label: 'Area', unit: 'sq units' },
    compute: v => Math.PI * v.r * v.r,
    format: num,
  },
  {
    id: 'circle-circumference',
    topic: 'geometry',
    name: 'Circle Circumference',
    desc: 'Perimeter of a circle',
    keywords: 'circle circumference perimeter pi radius round',
    eq: 'C = 2 · π · r',
    inputs: [
      { key: 'r', label: 'Radius', unit: '', hint: 'e.g. 5' },
    ],
    output: { label: 'Circumference', unit: 'units' },
    compute: v => 2 * Math.PI * v.r,
    format: num,
  },
  {
    id: 'triangle-area',
    topic: 'geometry',
    name: 'Triangle Area',
    desc: 'Area from base and height',
    keywords: 'triangle area base height half',
    eq: 'A = ½ · b · h',
    inputs: [
      { key: 'b', label: 'Base', unit: '', hint: 'e.g. 10' },
      { key: 'h', label: 'Height', unit: '', hint: 'e.g. 6' },
    ],
    output: { label: 'Area', unit: 'sq units' },
    compute: v => 0.5 * v.b * v.h,
    format: num,
  },
  {
    id: 'sphere-volume',
    topic: 'geometry',
    name: 'Sphere Volume',
    desc: 'Volume of a sphere',
    keywords: 'sphere volume ball radius round 3d',
    eq: 'V = 4⁄3 · π · r³',
    inputs: [
      { key: 'r', label: 'Radius', unit: '', hint: 'e.g. 3' },
    ],
    output: { label: 'Volume', unit: 'cubic units' },
    compute: v => (4 / 3) * Math.PI * Math.pow(v.r, 3),
    format: num,
  },
  {
    id: 'pythagoras',
    topic: 'geometry',
    name: 'Pythagorean Theorem',
    desc: 'Hypotenuse of a right-angled triangle',
    keywords: 'pythagoras pythagorean theorem hypotenuse right triangle sides',
    eq: 'c = √(a² + b²)',
    inputs: [
      { key: 'a', label: 'Side a', unit: '', hint: 'e.g. 3' },
      { key: 'b', label: 'Side b', unit: '', hint: 'e.g. 4' },
    ],
    output: { label: 'Hypotenuse (c)', unit: 'units' },
    compute: v => Math.sqrt(v.a * v.a + v.b * v.b),
    format: num,
  },
]);
