// generated by tools/build-pages.py - do not edit; edit js/ and re-run
// Built from js/formulas/*.js - edit those, then re-run.
registerIndex([
  {"id": "compound-interest", "topic": "finance", "name": "Compound Interest (Future Value)", "short": "Compound Interest", "desc": "What a lump sum grows to with compounding", "keywords": "compound interest future value savings investment growth apy deposit accumulate"},
  {"id": "fv-annuity", "topic": "finance", "name": "Future Value of an Annuity", "short": "Value of Annuity", "desc": "Value of equal recurring deposits", "keywords": "future value annuity sip regular deposits savings recurring ordinary retirement contributions"},
  {"id": "growing-annuity", "topic": "finance", "name": "Growing Annuity (Future Net Income)", "short": "Growing Annuity", "desc": "Recurring income growing at a constant rate, valued at a future point", "keywords": "growing annuity future net income stream growth rate recurring dividend pension retirement graduated"},
  {"id": "kinetic-energy", "topic": "mechanics", "name": "Kinetic Energy", "desc": "Energy of a moving object", "keywords": "kinetic energy motion moving joules velocity speed mass ke"},
  {"id": "loan-payment", "slug": "loan", "topic": "finance", "name": "Loan Payment Calculator", "short": "Loan Calculator", "desc": "Monthly payment for a fixed-rate loan or mortgage", "keywords": "mortgage loan emi installment repayment amortization home car borrow monthly payment principal debt"},
  {"id": "momentum", "topic": "mechanics", "name": "Momentum", "desc": "Quantity of motion", "keywords": "momentum motion impulse mass velocity collision p=mv"},
  {"id": "newtons-second-law", "topic": "mechanics", "name": "Newton's Second Law (Force)", "short": "Force (F = ma)", "desc": "Force from mass and acceleration", "keywords": "newton second law force mass acceleration f=ma dynamics push"},
  {"id": "potential-energy", "topic": "mechanics", "name": "Gravitational Potential Energy", "short": "Potential Energy", "desc": "Energy stored due to height", "keywords": "gravitational potential energy height gravity stored mgh pe"},
  {"id": "present-value", "topic": "finance", "name": "Present Value", "desc": "Today's worth of a future amount", "keywords": "present value discount pv discounting time value of money today worth npv"},
  {"id": "roi", "topic": "finance", "name": "Return on Investment (ROI)", "short": "ROI", "desc": "Total percentage return, including income received", "keywords": "roi return on investment profit gain loss percentage yield performance dividends interest income rent total return"},
  {"id": "work-done", "topic": "mechanics", "name": "Work Done", "desc": "Work from a force acting over a distance", "keywords": "work done force distance joules energy displacement"}
]);
