// generated by tools/build-pages.py - do not edit; edit js/ and re-run
// Built from js/formulas/*.js - edit those, then re-run.
registerIndex([
  {"id": "annuity", "topic": "finance", "name": "Annuity Calculator", "short": "Annuity", "desc": "What regular payments add up to by a future date", "keywords": "annuity future value regular payments deposits sip savings recurring contributions retirement pension growing graduated escalating income stream level ordinary compounding"},
  {"id": "compound-interest", "slug": "compound", "topic": "finance", "name": "Compound Interest (Future Value)", "short": "Compound Interest", "desc": "What a lump sum grows to with compounding", "keywords": "compound interest future value savings investment growth apy deposit accumulate"},
  {"id": "kinetic-energy", "slug": "kinetic", "topic": "mechanics", "name": "Kinetic Energy", "desc": "Energy of a moving object", "keywords": "kinetic energy motion moving joules velocity speed mass ke"},
  {"id": "loan-payment", "slug": "loan", "topic": "finance", "name": "Loan Payment Calculator", "short": "Loan Calculator", "desc": "Monthly payment for a fixed-rate loan or mortgage", "keywords": "mortgage loan emi installment repayment amortization amortisation home house car auto personal borrow monthly payment principal interest downpayment down payment debt fixed rate term extra payment payoff"},
  {"id": "momentum", "topic": "mechanics", "name": "Momentum", "desc": "Quantity of motion", "keywords": "momentum motion impulse mass velocity collision p=mv"},
  {"id": "newtons-second-law", "slug": "force", "topic": "mechanics", "name": "Newton's Second Law (Force)", "short": "Force (F = ma)", "desc": "Force from mass and acceleration", "keywords": "newton second law force mass acceleration f=ma dynamics push"},
  {"id": "potential-energy", "slug": "potential", "topic": "mechanics", "name": "Gravitational Potential Energy", "short": "Potential Energy", "desc": "Energy stored due to height", "keywords": "gravitational potential energy height gravity stored mgh pe"},
  {"id": "present-value", "topic": "finance", "name": "Present Value", "desc": "Today's worth of a future amount", "keywords": "present value discount pv discounting time value of money today worth npv"},
  {"id": "roi", "topic": "finance", "name": "Return on Investment (ROI)", "short": "ROI", "desc": "Total percentage return, including income received", "keywords": "roi return on investment profit gain loss percentage yield performance dividends interest income rent total return"},
  {"id": "work-done", "slug": "work", "topic": "mechanics", "name": "Work Done", "desc": "Work from a force acting over a distance", "keywords": "work done force distance joules energy displacement"}
]);
