/* Mechanics formulas. `num` comes from engine.js. */
registerFormulas([
  {
    id: 'kinetic-energy',
    topic: 'mechanics',
    name: 'Kinetic Energy',
    desc: 'Energy of a moving object',
    keywords: 'kinetic energy motion moving joules velocity speed mass ke',
    eq: 'KE = ½ · m · v²',
    inputs: [
      { key: 'm', label: 'Mass', unit: 'kg', hint: 'e.g. 1200' },
      { key: 'vel', label: 'Velocity', unit: 'm/s', hint: 'e.g. 25' },
    ],
    output: { label: 'Kinetic energy', unit: 'J' },
    compute: v => 0.5 * v.m * v.vel * v.vel,
    format: num,
  },
  {
    id: 'newtons-second-law',
    topic: 'mechanics',
    name: "Newton's Second Law (Force)",
    desc: 'Force from mass and acceleration',
    keywords: 'newton second law force mass acceleration f=ma dynamics push',
    eq: 'F = m · a',
    inputs: [
      { key: 'm', label: 'Mass', unit: 'kg', hint: 'e.g. 10' },
      { key: 'a', label: 'Acceleration', unit: 'm/s²', hint: 'e.g. 9.8' },
    ],
    output: { label: 'Force', unit: 'N' },
    compute: v => v.m * v.a,
    format: num,
  },
  {
    id: 'potential-energy',
    topic: 'mechanics',
    name: 'Gravitational Potential Energy',
    desc: 'Energy stored due to height',
    keywords: 'gravitational potential energy height gravity stored mgh pe',
    eq: 'PE = m · g · h',
    inputs: [
      { key: 'm', label: 'Mass', unit: 'kg', hint: 'e.g. 5' },
      { key: 'g', label: 'Gravity', unit: 'm/s²', hint: '9.81 on Earth' },
      { key: 'h', label: 'Height', unit: 'm', hint: 'e.g. 10' },
    ],
    output: { label: 'Potential energy', unit: 'J' },
    compute: v => v.m * v.g * v.h,
    format: num,
  },
  {
    id: 'momentum',
    topic: 'mechanics',
    name: 'Momentum',
    desc: 'Quantity of motion',
    keywords: 'momentum motion impulse mass velocity collision p=mv',
    eq: 'p = m · v',
    inputs: [
      { key: 'm', label: 'Mass', unit: 'kg', hint: 'e.g. 1200' },
      { key: 'vel', label: 'Velocity', unit: 'm/s', hint: 'e.g. 25' },
    ],
    output: { label: 'Momentum', unit: 'kg·m/s' },
    compute: v => v.m * v.vel,
    format: num,
  },
  {
    id: 'work-done',
    topic: 'mechanics',
    name: 'Work Done',
    desc: 'Work from a force acting over a distance',
    keywords: 'work done force distance joules energy displacement',
    eq: 'W = F · d · cos(θ)',
    inputs: [
      { key: 'F', label: 'Force', unit: 'N', hint: 'e.g. 50' },
      { key: 'd', label: 'Distance', unit: 'm', hint: 'e.g. 8' },
      { key: 'theta', label: 'Angle to direction of motion', unit: '°', hint: '0 if same direction' },
    ],
    output: { label: 'Work', unit: 'J' },
    compute: v => v.F * v.d * Math.cos(v.theta * Math.PI / 180),
    format: num,
  },
]);
