#!/usr/bin/env python3
"""Writes a real page for every formula, so useformula.com/loan-payment/ is a
file the server can hand over rather than a fragment only the browser can read.

GitHub Pages serves static files and nothing else: no rewrites, no redirects.
A visitor asking for /loan-payment/ gets loan-payment/index.html or a 404, so
every route needs a file of its own. Everything after a # never reaches the
server at all, which is why the old #formula/... links were invisible to search
engines: one page, one title, one description for the whole site.

Run from anywhere; paths are worked out from this file's location:

    python3 tools/build-pages.py

Reads the formulas from js/formulas/*.js and the shell from tools/shell.html,
then writes
    index.html                  the home page
    <slug>/index.html           e.g. loan/index.html
    topics/<topic-id>/index.html
    about/index.html
    404.html, sitemap.xml, robots.txt

Every generated file carries MARKER on its first line. Nothing without that
line is ever rewritten or deleted, so a hand-written file cannot be clobbered
by a stray run. Re-run after editing any formula's name, desc or eq.
"""

import hashlib
import html
import json
import re
import sys
from datetime import date, timezone, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHELL = Path(__file__).resolve().parent / 'shell.html'
SITE = 'https://useformula.com'
MARKER = '<!-- generated by tools/build-pages.py - do not edit; edit js/ and re-run -->'

# Fields read off a formula. Everything else (compute, series, sliders) only
# matters once the page is running, so it is left to the browser.
FIELDS = ('topic', 'name', 'short', 'slug', 'desc', 'keywords', 'eq',
          'title', 'blurb', 'diagram', 'diagramAlt')


def address(f):
    """Where a formula answers: its id, or its slug when it has one."""
    return f.get('slug') or f['id']


def changed(*names):
    """The day the newest of these source files was last touched, for the
    sitemap. Taken from the files rather than from today's date, so re-running
    the build does not tell search engines that unchanged pages are new."""
    stamp = max((ROOT / n).stat().st_mtime for n in names)
    return datetime.fromtimestamp(stamp, timezone.utc).date().isoformat()


def die(msg):
    sys.exit('build-pages: ' + msg)


def unquote(raw):
    """The value of a `key: '...'` line, with the JS escapes undone."""
    return raw.replace("\\'", "'").replace('\\"', '"').replace('\\\\', '\\')


def read_topics():
    src = (ROOT / 'js' / 'topics.js').read_text(encoding='utf-8')
    topics = []
    for line in src.splitlines():
        m = re.search(r"\{\s*id:\s*'([^']+)'", line)
        if not m:
            continue
        entry = {'id': m.group(1)}
        for key in ('icon', 'name', 'desc'):
            v = re.search(r"\b%s:\s*'([^']*)'" % key, line)
            if v:
                entry[key] = unquote(v.group(1))
        topics.append(entry)
    return topics


def read_formulas():
    """One dict per file in js/formulas/. Only the descriptive fields are read
    - the inputs and compute function are the browser's business. The files are
    hand-written in a steady shape (two spaces, `key: 'value',`), so this reads
    them line by line rather than pulling in a JavaScript engine."""
    formulas = []
    for path in sorted((ROOT / 'js' / 'formulas').glob('*.js')):
        current = None
        for line in path.read_text(encoding='utf-8').splitlines():
            m = re.match(r"^  id: '([^']+)',", line)
            if m:
                if current is not None:
                    die('%s holds more than one formula; one file each, named '
                        'after the id' % path.name)
                current = {'id': m.group(1), 'inputs': [],
                           'file': 'formulas/' + path.name}
                formulas.append(current)
                continue
            if current is None:
                continue
            m = re.match(r"""^  (%s): (['"])(.*)\2,?\s*$""" % '|'.join(FIELDS), line)
            if m:
                current[m.group(1)] = unquote(m.group(3))
                continue
            # `about: [ '…', '…' ]` spans lines. Collected here rather than
            # matched in one go, since the paragraphs are long and wrap.
            if line.startswith('  about: ['):
                current['_in_about'] = True
                current['about'] = []
                continue
            if current.get('_in_about'):
                if line.startswith('  ],'):
                    current.pop('_in_about')
                    continue
                m = re.match(r"^    (['\"])(.*)\1,?\s*$", line)
                if m:
                    current['about'].append(unquote(m.group(2)))
                continue
            # Input rows, for the sentence naming what the calculator asks for.
            # Advanced ones sit behind a panel, so they are left out of it.
            m = re.match(r"^    \{ key: '[^']+', label: (['\"])(.*?)\1", line)
            if m and 'advanced: true' not in line:
                current['inputs'].append(unquote(m.group(2)))
        if current is None:
            die('%s registers no formula (no `  id:` line)' % path.name)
        if current.get('_in_about'):
            die('%s has an `about:` block that never closes with `  ],`' % path.name)
        if current['id'] != path.stem:
            die('%s holds formula %r; the file must be named after the id'
                % (path.name, current['id']))
    return formulas


def read_const(name):
    """A string constant out of js/engine.js, so the served HTML and the
    rendered page cannot end up saying different things."""
    src = (ROOT / 'js' / 'engine.js').read_text(encoding='utf-8')
    m = re.search(r"^const %s = (.+?);$" % name, src, re.M | re.S)
    if not m:
        die('js/engine.js has no `const %s = ...;`' % name)
    parts = re.findall(r"'((?:[^'\\]|\\.)*)'", m.group(1))
    if not parts:
        die('could not read the value of %s from js/engine.js' % name)
    return unquote(''.join(parts))


def read_setting(key, default):
    src = (ROOT / 'js' / 'settings.js').read_text(encoding='utf-8')
    m = re.search(r'\b%s:\s*(true|false)' % key, src)
    return (m.group(1) == 'true') if m else default


def sentence(f):
    """A plain line saying what the calculator wants and what it gives back.
    Real text on the page, for a reader who arrives before the script does."""
    labels = [l.lower() for l in f.get('inputs', [])]
    if not labels:
        return ''
    if len(labels) == 1:
        asked = labels[0]
    else:
        asked = ', '.join(labels[:-1]) + ' and ' + labels[-1]
    return 'Enter %s to work out the %s.' % (asked, f['desc'][0].lower() + f['desc'][1:])


def breadcrumbs(trail):
    """Schema.org BreadcrumbList, matching the crumbs drawn on the page. This
    is what puts "useformula.com › Finance › Loan Payment Calculator" in a
    search result instead of a bare URL."""
    items = [{'@type': 'ListItem', 'position': i + 1, 'name': name, 'item': SITE + path}
             for i, (name, path) in enumerate(trail)]
    return json.dumps({'@context': 'https://schema.org',
                       '@type': 'BreadcrumbList',
                       'itemListElement': items}, ensure_ascii=False)


def head_block(title, description, canonical, trail, website=False):
    e = html.escape
    out = [
        '  <title>%s</title>' % e(title),
        '  <meta name="description" content="%s">' % e(description),
        '  <link rel="canonical" href="%s">' % e(canonical),
        '  <meta property="og:type" content="website">',
        '  <meta property="og:title" content="%s">' % e(title),
        '  <meta property="og:description" content="%s">' % e(description),
        '  <meta property="og:url" content="%s">' % e(canonical),
    ]
    if website:
        out += ['  <script type="application/ld+json">',
                '  ' + json.dumps({'@context': 'https://schema.org', '@type': 'WebSite',
                                   'name': 'useFormula', 'url': SITE + '/'}),
                '  </script>']
    elif trail:
        out += ['  <script type="application/ld+json">',
                '  ' + breadcrumbs(trail),
                '  </script>']
    return '\n'.join(out)


def stamp(rel):
    """The file's URL with a short hash of its contents on the end.

    Pages serves js and css with `cache-control: max-age=600`, so for ten
    minutes after a deploy a browser will use what it already has without
    asking. That is long enough to pair a fresh formula with the stale helper
    file it depends on - the formula calls a function the old helper has never
    heard of, compute throws, and the page loses its answer and its chart. A
    changed file gets a new address here, so that pairing cannot happen."""
    digest = hashlib.sha256((ROOT / rel).read_bytes()).hexdigest()[:8]
    return '/%s?v=%s' % (rel, digest)


def script_tags(f=None):
    """Every page needs the engine and the index. A calculator's page adds its
    topic's shared helpers, if that file exists, and then its own definition -
    and nothing else, so opening one calculator never downloads the rest."""
    src = ['js/settings.js', 'js/engine.js', 'js/topics.js', 'js/index.js']
    if f is not None:
        shared = 'js/shared/%s.js' % f['topic']
        if (ROOT / shared).exists():
            src.append(shared)
        src.append('js/%s' % f['file'])
    src.append('js/boot.js')
    return '\n'.join('<script src="%s"></script>' % stamp(u) for u in src)


def page(template, title, description, canonical, prerender,
         trail=None, formula=None, website=False, body_class=''):
    """The shell from index.html with this page's head and body dropped in."""
    out, n = re.subn(
        r'  <!-- page-head.*?  <!-- /page-head -->',
        lambda _: head_block(title, description, canonical, trail, website),
        template, flags=re.S)
    if n != 1:
        die('tools/shell.html has no <!-- page-head --> block to fill in')
    out, n = re.subn(r'<div id="app"></div>',
                     lambda _: '<div id="app">\n%s\n  </div>' % prerender, out)
    if n != 1:
        die('tools/shell.html has no empty <div id=\"app\"></div> to fill in')
    out, n = re.subn(r'<!-- page-scripts.*?<!-- /page-scripts -->',
                     lambda _: script_tags(formula), out, flags=re.S)
    if n != 1:
        die('tools/shell.html has no <!-- page-scripts --> block to fill in')
    out, n = re.subn(r'href="/styles\.css"',
                     lambda _: 'href="%s"' % stamp('styles.css'), out)
    if n != 1:
        die('tools/shell.html has no <link href="/styles.css"> to stamp')
    if body_class:
        out, n = re.subn(r'<body>', '<body class="%s">' % body_class, out)
        if n != 1:
            die('tools/shell.html has no plain <body> to put a class on')
    return MARKER + '\n' + out


def related_list(f, siblings):
    """Same links renderFormula draws once the script runs, so the crawler and
    the reader see the same thing. Every calculator added widens this net."""
    e = html.escape
    others = [o for o in siblings if o['id'] != f['id']]
    if not others:
        return []
    return (['    <nav class="related">',
             '      <h2>More %s calculators</h2>' % e(f['topic_name']),
             '      <ul>']
            + ['        <li><a href="/%s/">%s</a>\n        <span>%s</span></li>'
               % (address(o), e(o.get('short') or o['name']), e(o['desc'])) for o in others]
            + ['      </ul>', '    </nav>'])


def formula_prerender(f, topic, siblings, show_eq):
    e = html.escape
    bits = [
        '    <div class="crumbs"><a href="/">Home</a> › '
        '<a href="/topics/%s/">%s</a> › %s</div>' % (topic['id'], e(topic['name']), e(f['name'])),
        '    <div class="formula-box">',
        '      <div class="formula-head"><div class="formula-title">'
        '<h1>%s</h1></div></div>' % e(f['name']),
        '      <p class="sub">%s</p>' % e(f['desc']),
    ]
    if show_eq and f.get('eq'):
        bits.append('      <div class="eq">%s</div>' % e(f['eq']))
    if f.get('diagram'):
        bits.append('      <figure class="schematic"><img src="%s" alt="%s"></figure>'
                    % (e(f['diagram']), e(f.get('diagramAlt', ''))))
    line = sentence(f)
    if line:
        bits.append('      <p class="notes">%s</p>' % e(line))
    bits.append('    </div>')
    if f.get('about'):
        bits += ['    <section class="explainer">',
                 '      <h2>About %s</h2>' % e(f.get('short') or f['name'])]
        bits += ['      <p>%s</p>' % e(par) for par in f['about']]
        bits.append('    </section>')
    return '\n'.join(bits + related_list(f, siblings))


def topic_prerender(topic, formulas):
    e = html.escape
    links = '\n'.join(
        '      <li><a href="/%s/">%s</a> — %s</li>'
        % (f.get('slug') or f['id'], e(f['name']), e(f['desc']))
        for f in formulas)
    return '\n'.join([
        '    <div class="crumbs"><a href="/">Home</a> › %s</div>' % e(topic['name']),
        '    <h1>%s %s</h1>' % (topic.get('icon', ''), e(topic['name'])),
        '    <p class="sub">%s</p>' % e(topic['desc']),
        '    <ul class="prose">',
        links,
        '    </ul>',
    ])


def index_js(formulas):
    """Every formula, with only what a card, the search box or a related link
    needs. Loaded by every page, so it is kept to the descriptive fields."""
    keep = ('id', 'slug', 'topic', 'name', 'short', 'desc', 'keywords')
    rows = [{k: f[k] for k in keep if f.get(k)} for f in formulas]
    body = ',\n'.join('  ' + json.dumps(r, ensure_ascii=False) for r in rows)
    return ('// %s\n// Built from js/formulas/*.js - edit those, then re-run.\n'
            'registerIndex([\n%s\n]);\n' % (MARKER.strip('<!- >'), body))


def home_links(formulas):
    """Every calculator, named, in the served HTML. The app replaces this with
    the search box and the cards; it is here so the home page arrives with the
    site's contents in it rather than an empty div."""
    return ('    <ul class="prose">\n'
            + '\n'.join('      <li><a href="/%s/">%s</a></li>'
                        % (address(f), html.escape(f['name'])) for f in formulas)
            + '\n    </ul>')


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')
    print('  wrote %s' % path.relative_to(ROOT))


def clean_stale(keep):
    """Removes pages for formulas that no longer exist. Only files carrying
    MARKER are touched, so nothing hand-written is at risk."""
    for index in sorted(ROOT.glob('*/index.html')) + sorted(ROOT.glob('topics/*/index.html')):
        rel = index.relative_to(ROOT)
        if rel in keep or index.parent.name == 'js':
            continue
        if not index.read_text(encoding='utf-8').startswith(MARKER):
            continue
        index.unlink()
        try:
            index.parent.rmdir()
        except OSError:
            pass
        print('  removed stale %s' % rel)


def main():
    template = SHELL.read_text(encoding='utf-8')
    topics = read_topics()
    formulas = read_formulas()
    show_eq = read_setting('showEquation', True)

    if not topics:
        die('no topics found in js/topics.js')
    if not formulas:
        die('no formulas found in js/*.js - check the `id:` lines still start with four spaces')

    known = {t['id'] for t in topics}
    for f in formulas:
        for key in ('topic', 'name', 'desc'):
            if not f.get(key):
                die('formula %s in js/%s has no %s' % (f['id'], f['file'], key))
        if f['topic'] not in known:
            die('formula %s has topic %r, which is not in js/topics.js' % (f['id'], f['topic']))
    ids = [f['id'] for f in formulas]
    if len(set(ids)) != len(ids):
        die('two formulas share an id, so one page would overwrite the other')
    # A slug becomes a directory at the site root, so it must not collide with
    # another formula's address or with a path the site already uses.
    slugs = [f.get('slug') or f['id'] for f in formulas]
    if len(set(slugs)) != len(slugs):
        die('two formulas want the same address: ' + ', '.join(sorted(slugs)))
    # A slug becomes a directory at the site root, so it must not shadow a
    # file already sitting there (styles.css, sitemap.xml, CNAME, …) or one of
    # the directories the site reserves.
    reserved = {'topics', 'about', 'js', 'tools'}
    reserved |= {item.name for item in ROOT.iterdir() if item.is_file()}
    for s in slugs:
        if s in reserved:
            die('slug %r collides with a path the site already uses' % s)

    write(ROOT / 'js' / 'index.js', index_js(formulas))

    print('build-pages: %d formulas, %d topics' % (len(formulas), len(topics)))
    written = set()
    urls = [('%s/' % SITE, changed('tools/shell.html', 'js/engine.js'))]

    for f in formulas:
        topic = next(t for t in topics if t['id'] == f['topic'])
        f['topic_name'] = topic['name']
        siblings = [o for o in formulas if o['topic'] == f['topic']]
        slug = address(f)
        rel = Path(slug) / 'index.html'
        write(ROOT / rel, page(
            template,
            f.get('title') or '%s — useFormula' % f['name'],
            f.get('blurb') or
            '%s. Free online calculator: enter your values and get the answer.' % f['desc'],
            '%s/%s/' % (SITE, slug),
            formula_prerender(f, topic, siblings, show_eq),
            trail=[('Home', '/'), (topic['name'], '/topics/%s/' % topic['id']),
                   (f['name'], '/%s/' % slug)],
            formula=f))
        written.add(rel)
        urls.append(('%s/%s/' % (SITE, slug), changed('js/' + f['file'])))

    for t in topics:
        mine = [f for f in formulas if f['topic'] == t['id']]
        rel = Path('topics') / t['id'] / 'index.html'
        write(ROOT / rel, page(
            template,
            '%s Calculators — useFormula' % t['name'],
            '%s. %d free calculators: enter what you know and get the answer.' % (t['desc'], len(mine)),
            '%s/topics/%s/' % (SITE, t['id']),
            topic_prerender(t, mine),
            trail=[('Home', '/'), (t['name'], '/topics/%s/' % t['id'])],
            body_class='landing nocalc'))
        written.add(rel)
        urls.append(('%s/topics/%s/' % (SITE, t['id']),
                     changed('js/topics.js', *('js/' + f['file'] for f in mine))))

    rel = Path('about') / 'index.html'
    write(ROOT / rel, page(
        template,
        'About useFormula',
        'What useFormula is, how your favorites are stored, and the disclaimer that applies to every result.',
        '%s/about/' % SITE,
        # Heading only. The prose lives in renderAbout() in js/engine.js and is
        # drawn from there, so there is never a second copy to keep in step.
        '    <div class="crumbs"><a href="/">Home</a> › About</div>\n'
        '    <div class="prose"><h1>About useFormula</h1></div>',
        trail=[('Home', '/'), ('About', '/about/')], body_class='nocalc'))
    written.add(rel)
    urls.append(('%s/about/' % SITE, changed('js/engine.js')))

    write(ROOT / 'index.html', page(
        template,
        'Free Loan, Savings & Engineering Calculators — useFormula',
        'Free calculators for loan payments, compound interest, annuities, savings '
        'goals, pressure vessels and rotating disks. No sign-up, nothing to install.',
        '%s/' % SITE,
        '    <h1>%s</h1>\n    <p class="sub">%s</p>\n%s'
        % (html.escape(read_const('HOME_TITLE')), html.escape(read_const('HOME_INTRO')),
           home_links(formulas)),
        website=True, body_class='landing nocalc'))

    write(ROOT / '404.html', page(
        template,
        'Page not found — useFormula',
        'That page does not exist. Browse the calculators from the useFormula home page.',
        '%s/404.html' % SITE,
        '    <div class="prose"><h1>Page not found</h1>\n'
        '      <p>That address does not match any calculator. '
        '<a href="/">Start from the home page</a>.</p></div>',
        body_class='nocalc'))

    write(ROOT / 'sitemap.xml', '\n'.join(
        ['<?xml version="1.0" encoding="UTF-8"?>',
         '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
        + ['  <url><loc>%s</loc><lastmod>%s</lastmod></url>' % u for u in urls]
        + ['</urlset>', '']))

    write(ROOT / 'robots.txt',
          'User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n' % SITE)

    clean_stale(written)
    print('build-pages: done, %d urls in the sitemap' % len(urls))


if __name__ == '__main__':
    main()
